
version: "3.8"

services:
  db:
    image: postgres:14.1
    # command: postgres -c config_file=/etc/postgresql/postgresql.conf
    restart: unless-stopped
    ports:
      - ${POSTGRES_PORT:-5432}:5432
    environment:
      POSTGRES_PASSWORD: ${PGPASSWORD:-password}
    volumes:
      - ./pg_data_loading:/pg_data_loading
      - ./pg_data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5